### ISSUE TITLE
HACKTOBERFEST - Add yourself in developer.json at RANDOM position

### ISSUE THREAD

**Issue by shreyas-a** [shreyas-a/awesome-developers#4]
**Happy Hacktoberfest**

1. Fork the repo & add your details in `developers.json`
2. Create a Pull Request & chill.

**Comment by chaintng** [comment]
review please :) 
https://github.com/shreyas-a/awesome-developers/pull/32

**Comment by rajuvishwas** [comment]
PR - https://github.com/shreyas-a/awesome-developers/pull/37

**Comment by jigarWala** [comment]
Added  my  entry ,please review :-)
